### ISSUE TITLE
the old project home is confusing

### ISSUE THREAD

**Issue by attila-lendvai** [lispbuilder/lispbuilder#47]
i spent several minutes browsing the code and reading stuff on the old google code site until i realized that it's obsolete.

suggestions:
 - remove the frontpage and only leave one big note that sends the reader to github.
 - if wiki is migrated then remove the wiki pages, leaving only a note
 - commit one last commit into the svn repo that warns people who wander there

i was already preparing a patch when i realized this.

cliki was also pointing to the old project page, but right now it's unreachable, therefore i cannot update it myself right now.

**Comment by elliottslaughter** [comment]
Yes, these are good things to do. I had gotten lazy since Google Code will be read-only in a couple of months anyway, but there is no need to confuse people in the mean time.

**Comment by attila-lendvai** [comment]
damn, right! i've also heard that it will be discontinued, but unfortunately it didn't struck me at that time.

we can only hope that when they go read-only then it will be displayed with a visible enough warning...

**Comment by elliottslaughter** [comment]
Ok, there should be a global redirect from all Google Code pages to Github. I'm still slightly unsatisfied with the way the redirect works but Google Code is going read-only soon anyway, so it's not like it's going to matter for long.
