### ISSUE TITLE
When SDL_ListModes returns -1, SDL:LIST-MODES signals an error (64bits)

### ISSUE THREAD

**Issue by christophejunke** [lispbuilder/lispbuilder#50]
As documented, `(sdl:list-modes)` may return a list of vectors, `NIL`, or `T`, following the behavior of the original [SDL_ListModes](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdllistmodes.html) function. The way the original function works is by returning a *pointer*, which can be the *value* -1 "if any dimension is okay for the given format.". That case corresponds to the `T` return value in the Lisp code.

However, -1 is hard-coded to be 4294967295, or more readably `#xFFFFFFFF`, which equals to -1 only on 32-bits architectures. The following patch should help understanding the problem and shows a possible fix to include 64-bits architectures. Maybe a more general solution exists.

```diff
---
 lispbuilder-sdl/sdl/video.lisp | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/video.lisp b/video.lisp
index a0d1706..817189f 100644
--- a/video.lisp
+++ b/video.lisp
@@ -283,7 +283,9 @@ Returns `T` if any dimension will support the pixel format and video flags.
           (listmodes (sdl-cffi::SDL-List-Modes (cffi:null-pointer) (apply #'logior flags))))
     (cond
       ((cffi:null-pointer-p listmodes) nil)
-      ((equal (cffi:pointer-address listmodes) 4294967295) t)
+      ((equal (cffi:pointer-address listmodes)
+              #+cffi-features:x86-64  #xFFFFFFFFFFFFFFFF
+              #+cffi-features:x86     #xFFFFFFFF) t)
       (t
        (do ((i 0 (1+ i)))
              ((cffi:null-pointer-p (cffi:mem-aref listmodes :pointer i)) (reverse modes))
-- 
1.8.2.rc3.16.gce432ca

**Comment by christophejunke** [comment]
A more general way would be to let CFFI compute the address of -1 at load-time.

        ((equal (cffi:pointer-address listmodes)
                (load-time-value (cffi:pointer-address
                                  (cffi:inc-pointer
                                   (cffi:make-pointer 0) -1))) t))

**Comment by Balooga** [comment]
I agree that having CFFI compute the -1 value is the better solution.

**Comment by elliottslaughter** [comment]
Sorry for taking so long. I applied your patch as 44cd19e.
