### ISSUE TITLE
lispbuilder-sdl-examples not build in latest SBCL

### ISSUE THREAD

**Issue by quicklisp** [lispbuilder/lispbuilder#70]
http://report.quicklisp.org/2019-02-21/failure-report/lispbuilder.html#lispbuilder-sdl-examples has the log

    ;     (LISPBUILDER-SDL:CAST FLOAT
    ;                           (SQRT
    ;                            (/ LISPBUILDER-SDL-EXAMPLES::STRENGTH
    ;                               LISPBUILDER-SDL-EXAMPLES::IVAL)))
    ; --> COERCE THE IF 
    ; ==>
    ;   (SB-KERNEL:%SINGLE-FLOAT SB-C::X)
    ; 
    ; caught WARNING:
    ;   Derived type of SB-C::X is (VALUES (OR (COMPLEX DOUBLE-FLOAT) (COMPLEX SINGLE-FLOAT)) &OPTIONAL), conflicting with its asserted type REAL.
    ;   See also:
    ;     The SBCL Manual, Node "Handling of Types"

**Comment by elliottslaughter** [comment]
Is there an error in that log? I see

```
; compilation unit aborted
;   caught 1 fatal ERROR condition
;   caught 1 WARNING condition
;   caught 2 STYLE-WARNING conditions
;   printed 189 notes
```

But then grepping for `error` doesn't bring up anything other than the backtrace.

**Comment by quicklisp** [comment]
The "caught WARNING:" line is the fatal part.

**Comment by quicklisp** [comment]
Any update on this?

**Comment by elliottslaughter** [comment]
@quicklisp I was not able to reproduce on SBCL 1.5.0 on macOS, but have pushed a change that (I hope) fixes the problem. Please test, and if the problem isn't fixed please give me an exact command line to reproduce the problem.

**Comment by elliottslaughter** [comment]
I'm assuming this is fixed since there wasn't any response, but please feel free to reopen if the issue persists.
