### ISSUE TITLE
"config.lisp"

### ISSUE THREAD

**Issue by RealSharpness** [lispbuilder/lispbuilder#73]
On this page it says "3. Download & save config.lisp (...)"
https://github.com/lispbuilder/lispbuilder/wiki/WindowsLispworks

But the link appears to be broken.

Could there be at least some hint on where to look for this?
Newbies like me may get confused and be unable to proceed.

**Comment by elliottslaughter** [comment]
Is Starter Pack even the way to go these days? That link doesn't resolve either (or does to a "this has moved" page), and Starter Pack isn't on the first page of Edi Weitz's Github results.

I think we should probably be recommending Quicklisp (https://www.quicklisp.org). That doesn't solve the issue of needing to install C libraries, but it handles everything else and has been the go-to modern way of installing Lisp libraries for a while.
